services:
  frontend:
    build:
      context: ./resources/js/FE
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
  
  frontend-dev:
    build:
      context: ./resources/js/FE
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./resources/js/FE:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

volumes:
  redis_data:
